### ISSUE TITLE
Milestone 3.2: Implement Dashboards

### ISSUE THREAD

**Issue by Into-The-Grey** [Into-The-Grey/GHS-Website#9]
### Tasks:
- [ ] Task 1: Design and implement dashboards for each role using Next.js and React
  - [ ] Sub-task 1: Super Admin Dashboard
  - [ ] Sub-task 2: Admin Dashboard
  - [ ] Sub-task 3: Moderator Dashboard
  - [ ] Sub-task 4: Developer Dashboard
  - [ ] Sub-task 5: Helper Dashboard
  - [ ] Sub-task 6: Content Manager Dashboard
  - [ ] Sub-task 7: SEO Specialist Dashboard
  - [ ] Sub-task 8: Community Manager Dashboard
  - [ ] Sub-task 9: Expert Dashboard
  - [ ] Sub-task 10: User Dashboard
